### PR TITLE
Support ghc 9.12

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by erikd** [comment]
I have added a workaround to prevent the `cabal` solver pulling in an old (0.9.*) version of `aeson`.

**Comment by erikd** [comment]
This time for sure.

**Comment by erikd** [comment]
Added an extra:
```
if impl (ghc >= 9.12)
  constraints:
    , aeson >= 2
```

**Review by Ericson2314 — APPROVED** [review]

**Comment by erikd** [comment]
@Ericson2314 Can the metadata on Hackage also be updated.

**Pull request merged**
