### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by erikd**
Need this to to build this package as part of making a large project build with `ghc-9.8`.

There are a couple of compiler warnings, but it builds.

Since this only changes dependencies, I would really appreciate a Hackage metadata edit.

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
@erikd I just merged the previous one. the only seems to be this bump the TH upper bound slightly higher. Is that still needed?

**Comment by erikd** [comment]
Yes, the TH bounds bump is needed to build with `ghc-9.8`.

**Comment by Ericson2314** [comment]
I see that TH version doesn't exist. I did a hackage release and everything should be good now (I hope!).

**Comment by erikd** [comment]
Yep all good. Thanks!

**Pull request closed without merging**
